Repository puppetlabs/pdk-vanagon, pull requests merged in 2023-01, with the labels that each got.

#305 (CONT-413) Reset pdk rubygem version
  configs/components/pdk-templates.json
  configs/components/rubygem-pdk.json
Labels: maintenance

#306 (CONT-413) Bump additional ruby version
  configs/components/rubygem-json_pure_r27.rb
Labels: maintenance

#307 (CONT-422) PDK v2.6.0
  Gemfile
  configs/components/gem-prune.rb
  configs/components/pdk-templates.json
  configs/components/pdk-templates.rb
  configs/components/puppet-specifications.rb
  configs/components/puppet-versions.rb
  configs/components/rubygem-mini_portile2.rb
  configs/components/rubygem-nokogiri.rb
  configs/components/rubygem-pdk.json
  configs/platforms/fedora-36-x86_64.rb
  configs/projects/pdk.rb
Labels: enhancement

#309 (CONT-507) Add OSX 12 platform
  configs/platforms/osx-12-x86_64.rb
Labels: enhancement

#310 (CONT-513) Add Ubuntu 22.04 platform file
  configs/platforms/ubuntu22.04-amd64.rb
Labels: enhancement

#311 Fix Ubuntu 22.04 platform filename
  configs/platforms/ubuntu-22.04-amd64.rb
Labels: bug
